/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2018 MediaTek Inc.
 * Author: Houlong Wei <houlong.wei@mediatek.com>
 *
 */

#ifndef _DT_BINDINGS_GCE_MT8167_H
#define _DT_BINDINGS_GCE_MT8167_H

/* GCE HW thread priority */
#define CMDQ_THR_PRIO_LOWEST	0
#define CMDQ_THR_PRIO_HIGHEST	1

/* GCE SUBSYS */
#define SUBSYS_1300XXXX         0 // g3d
#define SUBSYS_1400XXXX		1 // mmsys
#define SUBSYS_1401XXXX		2 // disp-dither
#define SUBSYS_1402XXXX 	3 // mm-na
#define SUBSYS_1500XXXX         4 // imgsys
#define SUBSYS_1600XXXX		5 // vdec-gcon
#define SUBSYS_1700XXXX		6 // venc-gcon
#define SUBSYS_1800XXXX		7 // conn-peri
#define SUBSYS_1000XXXX		8 // topckgen
#define SUBSYS_1001XXXX		9 // kp
#define SUBSYS_1002XXXX		10 // scp-sram
#define SUBSYS_1003XXXX		11 // infra-na3
#define SUBSYS_1004XXXX		12 // infra-na4
#define SUBSYS_1005XXXX		13 // scp
#define SUBSYS_10200XXX		14 // mcucfg
#define SUBSYS_1020DXXX		15 // gcpu
#define SUBSYS_1120XXXX		16 // usb0
#define SUBSYS_1121XXXX		17 // usb0-sif
#define SUBSYS_1122XXXX		18 // audio
#define SUBSYS_1123XXXX		19 // msdc0
#define SUBSYS_1124XXXX		20 // msdc1
#define SUBSYS_1125XXXX		21 // msdc2
#define SUBSYS_1126XXXX		22 // msdc3
#define SUBSYS_1100FXXX		99 // pwm-sw

/* GCE HW EVENT */
#define CMDQ_EVENT_MDP_RDMA0_SOF		0
#define CMDQ_EVENT_MDP_RSZ0_SOF			1
#define CMDQ_EVENT_MDP_RSZ1_SOF			2
#define CMDQ_EVENT_MDP_TDSHP_SOF		3
#define CMDQ_EVENT_MDP_WDMA_SOF			4
#define CMDQ_EVENT_MDP_WROT_SOF			5

#define CMDQ_EVENT_DISP_OVL0_SOF		6
#define CMDQ_EVENT_DISP_RDMA0_SOF		8
#define CMDQ_EVENT_DISP_RDMA1_SOF		9
#define CMDQ_EVENT_DISP_WDMA0_SOF		10
#define CMDQ_EVENT_DISP_CCORR_SOF		11
#define CMDQ_EVENT_DISP_COLOR_SOF		12
#define CMDQ_EVENT_DISP_AAL_SOF			13
#define CMDQ_EVENT_DISP_GAMMA_SOF		14
#define CMDQ_EVENT_DISP_DITHER_SOF		15
#define CMDQ_EVENT_DISP_UFOE_SOF		16
#define CMDQ_EVENT_DISP_PWM0_SOF		17

#define CMDQ_EVENT_MDP_RDMA0_FRAME_DONE		18
#define CMDQ_EVENT_MDP_RSZ0_FRAME_DONE		19
#define CMDQ_EVENT_MDP_RSZ1_FRAME_DONE		20
#define CMDQ_EVENT_MDP_TDSHP_FRAME_DONE		21
#define CMDQ_EVENT_MDP_WDMA_FRAME_DONE		22
#define CMDQ_EVENT_MDP_WROT_WRITE_FRAME_DONE	23
#define CMDQ_EVENT_MDP_WROT_READ_FRAME_DONE	24

#define CMDQ_EVENT_DISP_OVL0_FRAME_DONE		25
#define CMDQ_EVENT_DISP_RDMA0_FRAME_DONE	27
#define CMDQ_EVENT_DISP_RDMA1_FRAME_DONE	28
#define CMDQ_EVENT_DISP_WDMA0_FRAME_DONE	29
#define CMDQ_EVENT_DISP_CCORR_FRAME_DONE	30
#define CMDQ_EVENT_DISP_COLOR_FRAME_DONE	31
#define CMDQ_EVENT_DISP_AAL_FRAME_DONE		32
#define CMDQ_EVENT_DISP_GAMMA_FRAME_DONE	33
#define CMDQ_EVENT_DISP_DITHER_FRAME_DONE	34
#define CMDQ_EVENT_DISP_UFOE_FRAME_DONE	        35
#define CMDQ_EVENT_DISP_DPI0_FRAME_DONE	        36
#define CMDQ_EVENT_DISP_DPI1_FRAME_DONE	        37

#define CMDQ_EVENT_MUTEX0_STREAM_EOF		38
#define CMDQ_EVENT_MUTEX1_STREAM_EOF		39
#define CMDQ_EVENT_MUTEX2_STREAM_EOF		40
#define CMDQ_EVENT_MUTEX3_STREAM_EOF		41
#define CMDQ_EVENT_MUTEX4_STREAM_EOF		42
#define CMDQ_EVENT_MUTEX5_STREAM_EOF		43
#define CMDQ_EVENT_MUTEX6_STREAM_EOF		44
#define CMDQ_EVENT_MUTEX7_STREAM_EOF		45
#define CMDQ_EVENT_MUTEX8_STREAM_EOF		46
#define CMDQ_EVENT_MUTEX9_STREAM_EOF		47

#define CMDQ_EVENT_BUF_UNDERRUN_ENG_EVENT_0	48
#define CMDQ_EVENT_BUF_UNDERRUN_ENG_EVENT_1	49

#define CMDQ_EVENT_ISP_FRAME_DONE_P2_1  	66
#define CMDQ_EVENT_ISP_FRAME_DONE_P2_0		67

#define CMDQ_EVENT_SENINF_0_FIFO_FULL		73

#endif
